export const ENTERPRISE_STYLE_PRESETS = {
  modern: {
    name: "Modern",
    radii: 18,
    density: "spacious",
    spacing: 20,
    shadow: "0 18px 40px rgba(29, 62, 120, 0.10)",
    sectionShadow: "0 12px 28px rgba(29, 62, 120, 0.08)",
    palette: {
      primaryColor: "#1f5fd1",
      accentColor: "#4f87ff",
      backgroundColor: "#f7f9fc",
      neutralColor: "#eef2f7",
      borderColor: "#d7deea",
      surfaceColor: "#ffffff",
      surfaceMutedColor: "#f2f6fd",
    },
  },
  business: {
    name: "Business",
    radii: 14,
    density: "normal",
    spacing: 16,
    shadow: "0 16px 32px rgba(18, 61, 122, 0.12)",
    sectionShadow: "0 10px 24px rgba(18, 61, 122, 0.08)",
    palette: {
      primaryColor: "#123d7a",
      accentColor: "#3568c8",
      backgroundColor: "#f7f9fc",
      neutralColor: "#edf2f8",
      borderColor: "#cfd8e6",
      surfaceColor: "#ffffff",
      surfaceMutedColor: "#f4f7fc",
    },
  },
  professional: {
    name: "Professional",
    radii: 12,
    density: "normal",
    spacing: 16,
    shadow: "0 14px 30px rgba(22, 35, 59, 0.10)",
    sectionShadow: "0 10px 22px rgba(22, 35, 59, 0.08)",
    palette: {
      primaryColor: "#16233b",
      accentColor: "#2f7dd6",
      backgroundColor: "#fbfcff",
      neutralColor: "#edf1f8",
      borderColor: "#d5deea",
      surfaceColor: "#ffffff",
      surfaceMutedColor: "#f6f9ff",
    },
  },
  it: {
    name: "IT",
    radii: 10,
    density: "compact",
    spacing: 14,
    shadow: "0 16px 30px rgba(15, 76, 129, 0.10)",
    sectionShadow: "0 10px 22px rgba(15, 76, 129, 0.08)",
    palette: {
      primaryColor: "#0f4c81",
      accentColor: "#2a9df4",
      backgroundColor: "#f4f8fc",
      neutralColor: "#e9eff6",
      borderColor: "#c6d6e8",
      surfaceColor: "#ffffff",
      surfaceMutedColor: "#eef5fc",
    },
  },
  minimal: {
    name: "Minimal",
    radii: 20,
    density: "compact",
    spacing: 12,
    shadow: "0 14px 28px rgba(31, 45, 74, 0.08)",
    sectionShadow: "0 8px 18px rgba(31, 45, 74, 0.06)",
    palette: {
      primaryColor: "#1f2d4a",
      accentColor: "#4d6aa6",
      backgroundColor: "#fcfdff",
      neutralColor: "#f2f5fa",
      borderColor: "#e0e7f1",
      surfaceColor: "#ffffff",
      surfaceMutedColor: "#f7f9fd",
    },
  },
  dashboard: {
    name: "Dashboard",
    radii: 16,
    density: "compact",
    spacing: 14,
    shadow: "0 18px 40px rgba(29, 78, 216, 0.10)",
    sectionShadow: "0 12px 24px rgba(29, 78, 216, 0.08)",
    palette: {
      primaryColor: "#1d4ed8",
      accentColor: "#60a5fa",
      backgroundColor: "#f5f7fb",
      neutralColor: "#eef3fb",
      borderColor: "#d5deeb",
      surfaceColor: "#ffffff",
      surfaceMutedColor: "#f7faff",
    },
  },
  landing: {
    name: "Landing",
    radii: 24,
    density: "spacious",
    spacing: 24,
    shadow: "0 22px 44px rgba(16, 58, 103, 0.12)",
    sectionShadow: "0 14px 30px rgba(16, 58, 103, 0.08)",
    palette: {
      primaryColor: "#103a67",
      accentColor: "#3b82f6",
      backgroundColor: "#f7f9fc",
      neutralColor: "#edf2f8",
      borderColor: "#d7deea",
      surfaceColor: "#ffffff",
      surfaceMutedColor: "#f7fbff",
    },
  },
  editorial: {
    name: "Editorial",
    radii: 8,
    density: "spacious",
    spacing: 18,
    shadow: "0 16px 34px rgba(23, 23, 23, 0.08)",
    sectionShadow: "0 10px 22px rgba(23, 23, 23, 0.06)",
    palette: {
      primaryColor: "#171717",
      accentColor: "#4b5563",
      backgroundColor: "#fcfcfb",
      neutralColor: "#f1f1ef",
      borderColor: "#dedbd6",
      surfaceColor: "#ffffff",
      surfaceMutedColor: "#faf8f5",
    },
  },
};

export const getStylePreset = (style = "modern") => ENTERPRISE_STYLE_PRESETS[String(style || "modern").toLowerCase()] || ENTERPRISE_STYLE_PRESETS.modern;
